name: ebook_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.13
  get: ^4.6.1
  google_fonts: ^2.3.2
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  permission_handler: ^9.2.0
  get_storage: ^2.0.3
  persistent_bottom_nav_bar: any
  share: ^2.0.4
  xml2json: ^5.3.2
  epub_viewer: ^0.2.5
  floor: ^1.2.0
  freezed_annotation: any
  dio: ^4.0.4
  retrofit: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  floor_generator: ^1.2.0
  build_runner: any
  freezed: ^1.1.0
  retrofit_generator: any
  json_serializable: any

flutter:
  uses-material-design: true  

  assets:
    - assets/images/
